-- AlterTable
ALTER TABLE "Intent" ADD COLUMN     "actionType" TEXT NOT NULL DEFAULT 'WEBHOOK',
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "lastTriggered" TIMESTAMP(3),
ADD COLUMN     "triggerCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
